# SPDX-FileCopyrightText: 2024 Vincent Lequertier <vincent@vl8r.eu>, Voichita Maxim <voichita.maxim@creatis.insa-lyon.fr>
#
# SPDX-License-Identifier: MIT
log_dir: 'logs'

data:
  file_name: D:\Matteo\LM_data\line_-6_6cm3_511keV_10MBqx1s_noise10keV_LM.h5
  max_ARM_sigma: 0.12
  data_type: 'HDF5'
  # Energy of the source. If set to -1 the gamma energy is the deposited energy i.e. E1 + E2
  # E0: [140, 245, 364, 511]
  E0: 511
  n_events: 500_000
  starts_at: 0

# Cameras have scatterer layers normal on z axis, centered on the z axis, below the source
cameras:
  n_cameras: 1
  # Cameras scatterer have the same characteristics besides their positions
  common_attributes:
    material: LSO
    size: [5.113, 5.113, 2.0]
    frame_origin: [0,0,0]
  
    # Sector 0: 0° (on +X axis)
  position_0:
    Ox: [0, 0, 1]           # Vertical (up)
    Oy: [0, 1, 0]           # Tangent (counterclockwise)
    Oz: [-1, 0, 0]          # Normal (inward)
    center: [10, 0, 0]   # Detector center in world coords

  # Sector 1: 30°
  position_1:
    Ox: [0, 0, 1]
    Oy: [-0.5, 0.866, 0]
    Oz: [-0.866, -0.5, 0]
    center: [8.66, 5, 0]

  # Sector 2: 60°
  position_2:
    Ox: [0, 0, 1]
    Oy: [-0.866, 0.5, 0]
    Oz: [-0.5, -0.866, 0]
    center: [5, 8.66, 0]

  # Sector 3: 90° (on +Y axis)
  position_3:
    Ox: [0, 0, 1]
    Oy: [-1, 0, 0]
    Oz: [0, -1, 0]
    center: [0, 10, 0]

  # Sector 4: 120°
  position_4:
    Ox: [0, 0, 1]
    Oy: [-0.866, -0.5, 0]
    Oz: [0.5, -0.866, 0]
    center: [-5, 8.66, 0]

  # Sector 5: 150°
  position_5:
    Ox: [0, 0, 1]
    Oy: [-0.5, -0.866, 0]
    Oz: [0.866, -0.5, 0]
    center: [-8.66, 5, 0]

  # Sector 6: 180° (on -X axis)
  position_6:
    Ox: [0, 0, 1]
    Oy: [0, -1, 0]
    Oz: [1, 0, 0]
    center: [-10, 0, 0]

  # Sector 7: 210°
  position_7:
    Ox: [0, 0, 1]
    Oy: [0.5, -0.866, 0]
    Oz: [0.866, 0.5, 0]
    center: [-8.66, -5, 0]

  # Sector 8: 240°
  position_8:
    Ox: [0, 0, 1]
    Oy: [0.866, -0.5, 0]
    Oz: [0.5, 0.866, 0]
    center: [-5, -8.66, 0]

  # Sector 9: 270° (on -Y axis)
  position_9:
    Ox: [0, 0, 1]
    Oy: [1, 0, 0]
    Oz: [0, 1, 0]
    center: [0, -10, 0]

  # Sector 10: 300°
  position_10:
    Ox: [0, 0, 1]
    Oy: [0.866, 0.5, 0]
    Oz: [-0.5, 0.866, 0]
    center: [5, -8.66, 0]

  # Sector 11: 330°
  position_11:
    Ox: [0, 0, 1]
    Oy: [0.5, 0.866, 0]
    Oz: [-0.866, 0.5, 0]
    center: [8.66, -5, 0]

volume:
  volume_dimensions: [18.5, 18.5, 6.5] # In centimeters
  n_voxels: [37, 37, 13]
  # volume_dimensions: [16.2, 16.2, 3.2] # In centimeters
  # n_voxels: [81, 81, 16]
  volume_centre: [0, 0, 0]

sensitivity:
  sub_N: [10,10,10]  # Number of subdivisions per detector for sensitivity calculation
  # sensitivity_model: solid_angle
  sensitivity_model: fake_list_mode
  sub_E: 10  # Energy splitting step in keV
  output_hdf5: sensitivity/test_sens.h5
  include_attenuation: 0
  save_dir: sensitivity
  file_name: 
  # file_name:

lm_algo:
  first_iter: 1
  last_iter: 500
  save_every: 5
  OSEM_n_subsets: 10
  batch_size: 10000 # Number of events to process in parallel

  cone_thickness: 'arm' #Either 'arm' or 'par'
  model: 'cos1rho2' # Either cos0rho0, cos0rho2 or cos1rho2. Use cos0rho0 if sensitivity is disabled.
  use_attenuation: 0

  save_dir: recons
  # save_file: test
  n_sigma: 2 # Skip the Gaussian above n_sigma * Gaussian std
  maximum_cone_thickness: 0.5 # In radians, set the cone to zero in arm mode
  width_factor: 1 # Used to artificially modify the spread of the cone

  use_sensitivity: 1
  sensitivity_file: sensitivity/sens_solid_angle_shape_37_37_13_subN_32_32_10_Attn_0.pth
  # sensitivity_file: sensitivity/sens_solid_angle_vol_10.1_10.1_2.1_subN_32_32_10_Attn_0.pth

  tv: false
  alpha_tv: 0.000
 