#!/bin/bash
#PBS -l walltime=15:00:00
#PBS -N coresi
#PBS -l nodes=1:gpu24:ppn=1:gpus=1
#PBS -q gpu
#PBS -l mem=16gb
#PBS -o coresi_stdout_tests.txt
#PBS -e coresi_stdout_tests.txt
#PBS -m ae
#PBS -M vincent.lequertier@creatis.insa-lyon.fr

set -e

cd "${PBS_O_WORKDIR}"
hostname
#conda env create -f conda-env.yaml --quiet || conda env update -f conda-env.yaml --quiet
eval "$(conda shell.bash hook)"
conda activate coresi
python -m tests.test_all_configs
