#!/bin/bash
#PBS -l walltime=15:00:00
#PBS -N coresi
#PBS -l nodes=1:ppn=32
#PBS -l mem=16gb
#PBS -o coresi_stdout.txt
#PBS -e coresi_stdout.txt
#PBS -m ae
#PBS -M vincent.lequertier@creatis.insa-lyon.fr

set -e

cd "${PBS_O_WORKDIR}"
hostname
conda env create -f conda-env.yaml --quiet || conda env update -f conda-env.yaml --quiet
eval "$(conda shell.bash hook)"
conda activate coresi
python src/main.py
